apiVersion: v1
kind: Namespace
metadata:
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
  name: prod
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: prod
spec:
  interval: 10m
  timeout: 1m
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-test
  namespace: prod
  annotations:
    fluxcd.io/ignore: "false"
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: prod
      version: 2.0.0
  install:
    createNamespace: true
    remediation:
      retries: 30
  interval: 15s
  releaseName: nginx-test
  targetNamespace: prod
  upgrade:
    remediation:
      retries: 30
  values:
    controller:
      service:
        type: LoadBalancer
---
